---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangds.
--- DateTime: 2021/7/21 16:31
---
local userid=KEYS[1];
local prodid=KEYS[2];
local qtkey="sk:"..prodid..":qt";
local usersKey="sk:"..prodid..":usr";
local userExists=redis.call("sismember", usersKey, userid);
if userExists.tonumber()==1 then
    return 2;
end
local num= redis.call("get", qtkey);
if num.tonumber()<=0 then
    return 0;
else
    redis.call("decr", qtkey);
    redis.call("sadd", usersKey, userid);
end
return 1;