---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangds.
--- DateTime: 2020/8/19 11:00
---

-- unlock key
local key     = KEYS[1]
local content = KEYS[2]
local value = redis.call('get', key)
if value == content then
    --  redis.call('decr', "count")
    return redis.call('del', key);
end
return 0
